chimple/cuba

src/components/ChapterCard.css
src/components/LessonCard.css
src/index.css
src/pages/Profile.css
src/pages/Profile.tsx
src/theme/variables.css

Updated Text color to #182A4F

---

public/courses/sl_en1_mp/course.json
public/courses/sl_en2_mp/course.json
public/courses/sl_maths1_mp/course.json
public/courses/sl_maths2_mp/course.json
src/components/LessonCard.tsx

Fixes #135 and also added missing colors to courses json files

---

src/App.tsx
src/components/ChapterBar.css
src/components/ChapterBar.tsx
src/components/ChapterDropDown.tsx
src/components/GradeDropDown.tsx
src/components/LessonSlider.tsx
src/pages/Home.tsx
src/utility/util.ts

Added Chapter drop down and Storing lesson bundles on android data folder

---

package-lock.json
package.json

This reverts commit b68d3167a9f290325f81c741582534aca89b0a40.

Revert "account manager changes in package-lock.json"

---

src/components/HomeHeader.tsx
src/components/ProfileHeader.tsx
src/models/auth.ts

Showing username in profile page and  Home header

---

src/App.tsx
src/common/constants.ts
src/common/courseConstants.ts
src/components/TextBox.tsx
src/components/common/BackButton.css
src/components/common/BackButton.tsx
src/components/parent/ParentHeader.css
src/components/parent/ProfileCard.tsx
src/components/studentProgress/StudentProgressHeader.css
src/components/studentProgress/StudentProgressHeader.tsx
src/pages/Login.tsx
src/pages/Parent.tsx
src/pages/Profile.tsx
src/pages/StudentProgress.css
src/pages/StudentProgress.tsx
src/services/api/ApiHandler.ts
src/services/api/FirebaseApi.ts
src/services/api/OneRosterApi.ts
src/services/api/ServiceApi.ts

Added Student Progress Report

---

package-lock.json
src/components/parent/ParentalLock.css

change the background the color of numbers to green when clicked

change the background the color of numbers to green when clicked

---

firebase.json
src/pages/DisplayStudents.css
src/pages/DisplayStudents.tsx

Completed Fix the 14-letter character to the child’s name on the login screen...

Completed Fix the 14 letter characters

---

src/components/IconButton.css
src/components/IconButton.tsx

Completed Fix the 14-letter character to the child name on the home screen...

Fix the 14 letter character to the child name on the home screen..

---

src/components/parent/ParentalLock.css
src/components/parent/ParentalLock.tsx
src/theme/variables.css

updating the unlock button functionality and color

unlock button

---

src/components/parent/ProfileCard.css
src/components/parent/ProfileCard.tsx
src/pages/Leaderboard.css
src/pages/Leaderboard.tsx

Completed fixed 14 character issues parent screen

fixed 14 character issues in parent screen in  completed

---

src/components/TextBox.css
src/pages/Login.css

The gap between the input tag and "get OTP" button. Updated the Gmail button size to smaller,  Adjusted The "get OTP" button size to align with the input field.

Updated login screen

---

src/components/ChimpleLogo.css
src/components/DropDown.css
src/components/TextBox.css
src/components/editStudent/GradeBoardAndLangDropdown.css
src/pages/EditStudent.tsx

UI enhancement- Text changes

---

src/components/DropDown.css
src/pages/Leaderboard.tsx

Fixed the Dropdown issue and in leaderboard orange band also fixed

Fixed the Dropdown issue and in leaderboard orange band also fixed

---

src/pages/Login.tsx

Removed the Parent name page asking

Removed the Parent name page asking

---

src/pages/Leaderboard.tsx

Updated leaderboard Dropdown

---

src/services/auth/FirebaseAuth.ts

Replace phone verifier with FirebaseAuthentication.confirmVerificationCode

---

src/pages/SearchLesson.tsx

After completing a lesson now stars and loved icons are coming

After completing a lesson now stars and loved icons are coming

---

src/components/IconButton.css

Fix the 14-letter character to the student name on the home screen

Fix the 14-letter character to the student name on the home screen

---

public/locales/en/translation.json
public/locales/hi/translation.json
src/components/parent/ProfileCard.tsx
src/pages/Home.tsx
src/pages/Leaderboard.css
src/pages/Leaderboard.tsx
src/pages/Parent.css

Added loading to deleting profile 
text color for FAQ

Moved leaderboard to profile in master

---

src/components/LessonSlider.tsx
src/pages/DisplaySubjects.tsx

Moved the logic from LesssonSlider to DisplaySubjects page.

Subjects automatically scroll to last played one

---

src/components/LessonSlider.css
src/components/LessonSlider.tsx
src/pages/EditStudent.css

Removed the extra padding in avatar screen

---

src/components/LessonSlider.css
src/components/LessonSlider.tsx
src/pages/EditStudent.css

Removed extra padding in avatar screen master

---

src/App.tsx
src/pages/Home.tsx

https://github.com/chimple/cuba/assets/134258437/a1bf2ad5-2d37-4010-8a64-470a39597d1b

DeepLink support In HomeScreen for Assignment and JoinClass

---

src/pages/EditStudent.tsx

User Profile will be Created if Gender is Specified

---

src/components/HomeHeader.tsx
src/pages/Home.tsx
src/services/RemoteConfig.ts

Developed Support In Home Screen Weather to Show Avatar or Suggestions

---

src/components/LessonCard.css
src/components/LessonCard.tsx
src/components/LessonCardStarIcons.css
src/components/LovedIcon.css

Alignment Of Loved Icon

---

src/pages/LiveQuiz.tsx
src/services/api/ApiHandler.ts
src/services/api/FirebaseApi.ts
src/services/api/OneRosterApi.ts
src/services/api/ServiceApi.ts

Filtered assignments by completed students

Removed the played quizzes from quiz body

---

src/models/assignment.ts
src/pages/Home.tsx
src/pages/Leaderboard.tsx
src/pages/LiveQuizLeaderBoard.css
src/pages/LiveQuizRoom.css
src/pages/LiveQuizRoom.tsx
src/pages/LiveQuizRoomResult.tsx
src/pages/StudentProgress.tsx
src/services/api/FirebaseApi.ts

Quizzes will appear in suggestions once it started
Removed scrolling for room result page
Fixes some UI issues in live quiz room page
Added outcome

Fixes live quiz issues

---

src/components/animation/ChimpleAvatar.css
src/components/animation/ChimpleAvatar.tsx
src/components/animation/TextBoxWithAudioButton.tsx

rive avatar chatbox transition animation in home screen

---

src/models/user.ts
src/utility/util.ts

 Adding usernamePhone or usernameMail for user while creating the user

---

src/components/HomeHeader.tsx
src/pages/LiveQuizLeaderBoard.tsx
src/pages/LiveQuizRoom.tsx
src/pages/LiveQuizRoomResult.tsx

Quiz tab will display after joining to class

---

src/components/common/StudentAvatar.tsx
src/pages/LiveQuizRoom.css
src/pages/LiveQuizRoom.tsx

UI issues are fixed and displaying chapter title in detail page of live quiz

---

src/components/animation/ChimpleAvatar.tsx

fixes Colour is not highlighting on the buttons in Avatar dialogue box.#1179

---

src/components/SkeltonLoading.css
src/components/SkeltonLoading.tsx
src/pages/LiveQuizLeaderBoard.css
src/pages/LiveQuizLeaderBoard.tsx
src/pages/LiveQuizRoom.css
src/pages/LiveQuizRoom.tsx

added back button also in live quiz join page
fixes live quiz leaderboard header scrolling issue

Added skeleton effect to the students profiles in live quiz join page

---

src/components/HeaderIcon.tsx
src/components/HomeHeader.tsx
src/components/IconButton.css
src/pages/Home.tsx

removed the live quiz count in home work indicator

Indicator for live quiz

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
src/components/animation/Avatar.tsx
src/components/animation/AvatarImageOption.css
src/components/animation/AvatarImageOption.tsx
src/components/leaderboard/LeaderboardSticker.tsx
src/utility/util.ts

UI and text changes in avatar screen dialogue box

---

src/pages/DisplayStudents.tsx
src/pages/Leaderboard.css

new profile creating option removed in display student page and also fixed leaderboard alignment issue

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
src/components/common/StudentAvatar.tsx
src/components/liveQuiz/LiveQuizHeader.tsx
src/components/liveQuiz/LiveQuizNavigationDots.css
src/components/liveQuiz/LiveQuizNavigationDots.tsx
src/components/liveQuiz/LiveQuizQuestion.css
src/components/liveQuiz/LiveQuizQuestion.tsx
src/components/liveQuiz/LiveQuizStudentAvatar.tsx
src/pages/LiveQuizGame.css
src/pages/LiveQuizGame.tsx

modified live quiz game page UI

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
src/components/common/StudentAvatar.tsx
src/components/liveQuiz/LiveQuizHeader.tsx
src/components/liveQuiz/LiveQuizNavigationDots.css
src/components/liveQuiz/LiveQuizNavigationDots.tsx
src/components/liveQuiz/LiveQuizQuestion.css
src/components/liveQuiz/LiveQuizQuestion.tsx
src/components/liveQuiz/LiveQuizStudentAvatar.tsx
src/pages/LiveQuizGame.css
src/pages/LiveQuizGame.tsx

Live quiz game page UI changes for master

---

src/components/liveQuiz/LiveQuizStudentAvatar.tsx

Fixes live quiz UI alignment

---

src/components/leaderboard/LeaderboardBadges.tsx
src/components/leaderboard/LeaderboardBonus.tsx
src/components/leaderboard/LeaderboardRewards.tsx
src/components/leaderboard/LeaderboardSticker.tsx

fixes the navigation issue and rewards text issues

Fixes the rewards page issues

---

src/components/liveQuiz/LiveQuizHeader.tsx
src/components/liveQuiz/LiveQuizQuestion.tsx
src/components/liveQuiz/LiveQuizStudentAvatar.tsx
src/pages/Home.tsx
src/pages/LiveQuizGame.tsx
src/pages/LiveQuizLeaderBoard.tsx
src/pages/LiveQuizRoom.tsx
src/pages/LiveQuizRoomResult.tsx
src/services/api/ApiHandler.ts
src/services/api/ServiceApi.ts
src/services/api/SqliteApi.ts
src/services/api/SupabaseApi.ts

getting all the student data along with results
sorting live quizzes

Fixes the live quiz issues

---

src/components/animation/AvatarImageOption.tsx

Icon Size Increased

---

src/pages/Malta/AddStudent.css

fixed font size in create profile page  by removing overriding  CSS font-size properties

---

src/components/studentProgress/CustomAppBar.css
src/components/studentProgress/CustomAppBar.tsx
src/pages/LiveQuizRoom.css
src/pages/LiveQuizRoom.tsx
src/pages/Parent.tsx
src/pages/StudentProgress.css
src/pages/StudentProgress.tsx

fixes the selecting courses issue in student progress report page and moved the live quiz join button in middle of the screen

Added grade and curriculum title in student progress page

---

src/components/studentProgress/CustomAppBar.css
src/pages/StudentProgress.css
src/pages/StudentProgress.tsx

Given width for course and curriculum text

---

src/services/api/SqliteApi.ts

in suggestion screen updating and showing upcoming lesson instead of showing last played lesson

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
src/components/editStudent/GenderAndAge.css
src/components/editStudent/GenderAndAge.tsx
src/pages/EditStudent.tsx

Added unspecified option in gender selection page

---

src/common/CalendarPicker.css
src/common/CalendarPicker.tsx

Common calendar

---

src/pages/EditStudent.tsx
src/services/api/SqliteApi.ts

sorting board names in alphabetical order

---

src/pages/EditStudent.tsx
src/services/api/FirebaseApi.ts

sorting board names in alphabetical order in master

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
public/locales/mr/translation.json
src/components/Loading.css
src/components/Loading.tsx
src/pages/Login.tsx

adding wait message during initial login of supabase-apk #1900

---

src/pages/Leaderboard.tsx
src/pages/Parent.tsx

fixes parent language change issue after user switching

---

src/utility/util.ts

Fixes #1941 Blank screen appears when user click on lesson

Fixes #1941 Blank screen appears when user click on lesson

---

src/common/AddButton.tsx
src/pages/DisplaySubjects.tsx

mouseover on the plus button become little bigger

---

src/theme/variables.css

Added new variables for different font sizes to maintain consistency throughout the application pages.

New Variables for different font sizes

---

src/pages/DisplayChapters.tsx

fixes auto-scrolling issue 1989

---

src/services/api/ApiDataProcessor.ts
src/services/api/SqliteApi.ts
src/services/interface/ApiDataProcessorTypes.ts

working on new changes api interface and remove chimple-private folder

working on new changes api interface

---

src/pages/Home.tsx

https://chimple.cc/live-quiz
https://chimple.cc/assignment

Live quiz deeplink issue #2052

---

src/components/liveQuiz/LiveQuizQuestion.css
src/components/liveQuiz/LiveQuizQuestion.tsx

fixed font size in live quiz

---

src/utility/classUtil.ts

1. If the assignment does not belong to the class (i.e. belongsToClass is false), the background color will be grey (#C4C4C4) and no score will be shown.
2. If the assignment belongs to the class but there are no results or only a dummy result (score is null), the background will be white and no score will be shown.

report table background white doesn't show 0 value

---

android/app/src/main/AndroidManifest.xml
src/common/constants.ts
src/pages/Home.tsx
src/pages/Leaderboard.tsx

fixed deeplink redirect issue

---

src/pages/AddCourses.tsx
src/pages/DisplaySubjects.css

Fixed issue #2044 Text showing white colour in Darkmode

---

android/app/src/main/java/org/chimple/bahama/MyFirebaseMessagingService.java

fix the null value for messageTitle and messageBody for assign assignment

---

src/common/constants.ts
src/pages/SearchLesson.tsx

added search keyword tracking event logs

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
src/components/editStudent/GradeBoardAndLangDropdown.tsx
src/pages/EditStudent.tsx
src/pages/Parent.tsx

Language Order preserved same dropdowns in AppLangSelection, Parent, EditStudent

Language order preserved same for dropdowns, Fixed Issue #2039

---

src/components/displaySubjects/SelectCourse.tsx

Description: "Course displaying order is not correct It should be English, Maths, 3rd Language and digital skill(Or alphabetical)"

Courses are now displaying in the genric order

---

src/pages/CocosGame.tsx
src/pages/Home.tsx

fixed redirect to home after playing game

---

src/pages/Leaderboard.tsx

Fixed: Blank screen appears on subjects page after clicking on subjects icon 2159

Fixed: Blank screen appears on subjects page after clicking on subjects icon

---

src/components/parent/DialogBoxButtons.css
src/components/parent/DialogBoxButtons​.tsx

Updated CSS for Malta migration Logout DialogBox

---

src/pages/CocosGame.tsx

Getting error because of name and detail was undefine 
so, Set the default value for name and detail.

Blank Screen Appears on Exit from Lesson Card Before Completion #2147

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/org/chimple/bahama/MainActivity.java
android/app/src/main/java/org/chimple/bahama/NativeSSOPlugin.java
android/app/src/main/java/org/chimple/bahama/PortPlugin.java
android/app/src/main/java/org/chimple/bahama/RespectHttpClient.java
package.json
src/index.tsx
src/pages/Login.tsx
src/pages/SelectMode.tsx
src/services/ServiceConfig.ts
src/services/api/OneRosterApi.ts
src/services/api/SqliteApi.ts
src/services/auth/AuthHandler.ts
src/services/auth/FirebaseAuth.ts
src/services/auth/OneRosterAuth.ts
src/services/auth/ServiceAuth.ts
src/services/auth/SupabaseAuth.ts

- Added Respect SSO Config
- Added Respect Launcher Service
- Refactor Android Config for Respect Integration

refactor: config for respect api

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
public/locales/mr/translation.json
src/components/displaySubjects/SelectCourse.tsx
src/pages/Login.tsx

Without App kill will show toast with remaining time to enable sendOTP button
With restart will show toast "please wait 60 seconds before retrying"

Fixed keep on loading issue when we try to login back to back

---

src/components/displaySubjects/SelectCourse.tsx

https://github.com/user-attachments/assets/ad180a62-45f7-4cfc-be24-a7bd3fae1d31

Fixed Add subject button appears before subjects load

---

src/pages/Leaderboard.css

Fixed leaderboard student avatar alignment

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/org/chimple/bahama/MainActivity.java
android/app/src/main/java/org/chimple/bahama/OTPReceiver.java
android/app/src/main/java/org/chimple/bahama/PortPlugin.java
src/components/TextBox.tsx
src/pages/Login.tsx

https://github.com/user-attachments/assets/85d83545-7393-4914-bab6-7f5cff4d485a

feat: added automatic phone number reading and SMS retrieval

---

src/utility/util.ts

…p when clicked on notification #2240

Navigate to particular Live Quiz page and do not show Live Quiz Pop Up when clicked on notification #2240

---

firebase.json

Found one probable solution which can fix the url routing issue.

url routing

---

.github/workflows/build-dev.yml
.github/workflows/build-supabase.yml
package.json
src/App.tsx
src/common/constants.ts
src/pages/Home.tsx

Growthbook supabase

---

src/services/api/SqliteApi.ts

fixes sorted order of assignments in homework page

---

android/app/src/main/java/org/chimple/bahama/PortPlugin.java
src/pages/CocosGame.tsx
src/services/api/OneRosterApi.ts
src/utility/lessonUtils.tsx
src/utility/util.ts

- able to comeback to home page
- able to update the played lessons

fix : deeplink issues solved

---

src/services/api/SqliteApi.ts

fixed issue recently played lesson card is not displaying first in Liked tab

---

src/components/LessonCard.tsx

here currentcourse value initially not loading so we are calling getCurrentCourse when we click on lesson card.

fixed bandwise report issue

---

src/components/Home/DropdownMenu.css
src/components/Home/DropdownMenu.tsx

Wrap the inner dropdown items in a div that stops propagation so the main container's toggle isn't triggered.

fixed the bugs in dropdown

---

android/app/src/main/java/org/chimple/bahama/PortPlugin.java
package.json
public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
public/locales/mr/translation.json
src/pages/Parent.tsx
src/services/api/ApiHandler.ts
src/services/api/ServiceApi.ts
src/services/api/SqliteApi.ts
src/services/api/SupabaseApi.ts
src/teachers-module/components/DebugMode.css
src/teachers-module/components/DebugMode.tsx
src/utility/util.ts

Features
Number of Rows Synchronized (Pushed / Pulled)
Data Transferred (Server ➜ Client, MB)
Rows Pending Transfer
Local Database Size
After clicking 7 times on sound button Debug popup will shown then on confirm Debug mode will open Sync Now button — on failure, display synchronization logs Clear Downloaded Lessons Button
Number of lessons downloaded number With Size
Show class Id & class name of student
Show school Id & school name of student
Delete after 30 days from SQLite
Screen shot share option
#Debug PopUp
#Debug Mode
#Debug Screenshot

Added debug mode to show sync info #2372

---

src/components/LessonCard.css
src/pages/Assignment.css
src/pages/Assignment.tsx
src/pages/Home.tsx
src/pages/Leaderboard.css
src/pages/Leaderboard.tsx

added home background page for all remaining pages also

---

src/components/LoginWithEmail.css
src/pages/Login.css
src/pages/Login.tsx

UI fixes in login page

---

src/pages/StudentProgress.css

scroll issue fix

---

src/teachers-module/components/schoolUsers/SchoolUserDetail.css
src/teachers-module/components/schoolUsers/SchoolUserDetail.tsx
src/teachers-module/components/studentProfile/UserDetail.css
src/teachers-module/components/studentProfile/UserDetail.tsx

Fixed Avatar size issues when we switch from teacher to parent mode

---

src/pages/Home.tsx

language & age added as attributes. Tested & working.

Attribute addition - growthbook

---

src/common/constants.ts
src/components/Home/DropdownMenu.tsx
src/components/LearningPathway.tsx
src/components/learningPathway/PathwayStructure.tsx
src/pages/CocosGame.tsx

- added analytics events  "pathway_created", "pathway_completed", "pathway_course_changed" for Leaning Pathway.
- fixed lesson icon in learning path, added fallback image onError.

fix: added analytics for learning pathway

---

src/teachers-module/components/homePage/DashBoardStudentProgress.css

Fixes of timer UI

---

src/teachers-module/components/homePage/DashBoardStudentProgres.tsx
src/teachers-module/components/homePage/DashBoardStudentProgress.css

Student progress UI issue

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
public/locales/mr/translation.json
src/App.tsx
src/common/constants.ts
src/ops-console/components/Dashboard.tsx
src/ops-console/components/Sidebar.css
src/ops-console/components/Sidebar.tsx
src/ops-console/pages/SidebarPage.css
src/ops-console/pages/SidebarPage.tsx
src/stories/OpsConsole/Pages/SidebarPage.stories.ts

Working on Add Program Module Navigation Bar 
Ticket No. https://github.com/chimple/cuba/issues/2554

working on sidebar menu

---

public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
public/locales/mr/translation.json
src/ops-console/components/FilterSlider.css
src/ops-console/components/FilterSlider.tsx
src/ops-console/pages/ProgramPage.tsx

feat: improve FilterSlider UX, highlight selected filters
Added conditional highlight to filter dropdowns with selected values using a new CSS class

feat: improve FilterSlider UX, highlight selected filters

---

public/pathwayAssets/menuCross.svg
src/components/LearningPathway.tsx
src/components/learningPathway/PathwayModal.css
src/components/learningPathway/PathwayModal.tsx

https://github.com/user-attachments/assets/40116d39-0575-49b2-a941-7ced50330b7e

UI Update for Pathway Learning

---

src/components/parent/ProfileCard.tsx
src/pages/DisplayStudents.tsx

fix: fixed UI issues for autoProfile

---

src/common/constants.ts
src/index.tsx
src/ops-console/pages/ProgramDetailsPage.tsx
src/pages/Login.tsx
src/services/ServiceConfig.ts
src/services/api/ApiHandler.ts
src/services/api/FirebaseApi.ts
src/services/api/ServiceApi.ts
src/services/api/SqliteApi.ts
src/services/api/SupabaseApi.ts
src/services/database.ts
src/stories/OpsConsole/Pages/ProgramDetailsPage.stories.tsx

- Add more relevent mock data for ProgramDetailsPage.stories.ts
- Add method to check if user is a Program User
- Format the Model and Date in Program Detail Page
- Add method to switch api mode

Add method to switch api mode

---

src/ops-console/components/DataTableBody.css
src/ops-console/components/DataTableBody.tsx
src/ops-console/components/SelectedFilters.css
src/ops-console/pages/SchoolList.css
src/ops-console/pages/SchoolList.tsx

Fixes the alignment issues in school listing page

---

src/teachers-module/components/homePage/dashBoard/DashBoard.tsx

1. For "All subjects" Average time spent data has not been displayed accurately -- Done
2. For "All subjects" Average score data has  been displayed succcesfully -- Done
1. While selecting the All subjects the whole screen is loading -- Done
1. The count of students on the bands is not displaying

Changes in Dashboard for all subjects

---

src/ops-console/components/FilterSlider.tsx
src/ops-console/components/SchoolDetailsComponents/SchoolStudents.tsx
src/ops-console/components/SchoolDetailsComponents/SchoolTeachers.tsx
src/ops-console/pages/ProgramPage.tsx
src/ops-console/pages/SchoolList.tsx

Added filterConfigs prop to FilterSlider to dynamically render filter fields based on provided config.

feat: make FilterSlider component reusable via filterConfigs prop.

---

src/teachers-module/components/reports/ReportsTable.tsx
src/teachers-module/components/reports/TableRightHeader.tsx
src/teachers-module/components/reports/TableStudentData.tsx

Enhance teacher all as per all subject assignment, weekly monthly report - Done

Enhance teacher all as per all subject

---

public/assets/termsandconditions/TermsandConditionsofChimple.html
public/locales/en/translation.json
public/locales/hi/translation.json
public/locales/kn/translation.json
public/locales/mr/translation.json
src/components/learningPathway/PathwayModal.css
src/components/learningPathway/PathwayModal.tsx
src/components/learningPathway/TressureBox.css
src/components/learningPathway/chapterLessonBox.tsx
src/components/signup/LanguageDropdown.css
src/components/signup/LoginSwitch.css
src/components/signup/LoginSwitch.tsx
src/components/signup/LoginWithEmail.css
src/components/signup/LoginWithPhone.css
src/components/signup/LoginWithStudentID.css
src/components/signup/OtpVerification.css
src/components/signup/OtpVerification.tsx
src/index.tsx
src/pages/LoginScreen.css
src/pages/LoginScreen.tsx

-Fixed resend otp button
-fixed Ui issues in login screens.
-The : between chapter name & lesson name now has proper spacing
-Remove the leaves in all the popups.
-The text of the treasure box changed to Baloo2 font.
-The popup of the reward box now changed  to have a cross for closing.
-Added slide in of the popup on click of the mystery rewards box in pathway.

fix: fixed resend otp and UI issues

---

src/teachers-module/components/homePage/dashBoard/DashBoard.tsx
src/teachers-module/components/reports/ReportsTable.tsx
src/teachers-module/components/reports/TableStudentData.tsx

1. Selecting "All subjects" not displaying accurate results in the bands - Done
2. "All subjects"-->Monthly report--> report data is not displaying -- done 
3. "All subjects"-->Weekly report--> report data is not displaying -- Done 
4. Monthly report should  be displayed and if we select "all activities", results should get for all assignments and non assignments -- Done

Working on displaying accurate results in the bands

---

src/teachers-module/components/homePage/dashBoard/DashBoard.tsx
src/teachers-module/components/imageDropdown.css
src/teachers-module/components/imageDropdown.tsx

For "All subjects" Active students data has been displayed successfully - Done
by selecting the chapter report first, then all subjects option should be disabled - Done

Active student visiable based on the bands in all subject

---

src/ops-console/pages/SchoolList.css
src/ops-console/pages/SchoolList.tsx

- pagination fixed at bottom of page
- given support for portrait mode
- added bell icon and fixed header

UI fixes of school listing

---

src/ops-console/OpsUtility/CheckWhatsapp.ts
src/pages/Login.tsx
src/pages/LoginScreen.tsx
src/pages/SelectMode.tsx
src/services/api/ApiHandler.ts
src/services/api/ServiceApi.ts
src/services/api/SqliteApi.ts
src/services/api/SupabaseApi.ts
src/services/auth/SupabaseAuth.ts
src/teachers-module/components/homePage/SideMenu.tsx
src/teachers-module/components/schoolUsers/SchoolUserList.tsx
src/teachers-module/components/studentProfile/UserList.tsx
src/teachers-module/pages/ClassProfile.tsx
src/teachers-module/pages/ClassUsers.tsx
src/teachers-module/pages/DisplaySchools.tsx
src/teachers-module/pages/ManageClass.tsx
src/utility/util.ts

https://github.com/user-attachments/assets/ff92f3a5-aeb9-4bd8-923c-4862983ea0b4
**NonNullable<typeof role>** ensures null is filtered out properly.

fixed flickering login issue

---

src/components/learningPathway/PathwayStructure.tsx

when user change the subject in learning pathway subject dropdown it is taking time to display the lessons related to the selected subject. - Done 
Improvements:
1. Parallel Loading: All assets are loaded in parallel using Promise.all to minimize waiting time.
2. Document Fragment: Uses a document fragment to batch DOM operations, reducing reflows and repaints.
3. Performance Monitoring: Added performance measurement to identify bottlenecks.
4. Mobile Considerations: Reduced synchronous operations that can block the UI thread on mobile devices.
5. Animation Optimization: Streamlined the gift animation sequence.
Recommendations: 
1. Lazy Loading: Consider loading only visible portions of the pathway initially.
2. Implement Caching: Cache SVG assets and lesson data to avoid repeated network …

Working on Syncing issue in the leaning pathway

---

src/services/api/SqliteApi.ts
src/teachers-module/components/homePage/dashBoard/DashBoard.tsx
src/utility/classUtil.ts

1. count and percentage of active students is invalid -- Done
2. only recent assigned assignments data is updating in bands - Its not updating from API data is not coming from Backend

Enhance Teacher Dashboard For individual and all subject

---

src/components/learningPathway/PathwayStructure.tsx

syncing issue pathway updating lessons card with cache here i used 
1. On first load, data will cache in memory + sessionStorage. 
2. On subsequent loads, lessons load from memory or sessionStorage instantly.
3. SVG lesson images will appear more smoothly due to preloading.
https://github.com/user-attachments/assets/716aa4a9-f171-4d37-91c4-98384892ae0f

Syncing issue pathway updating lessons card with cache

---

src/teachers-module/pages/EditClass.tsx

https://github.com/user-attachments/assets/1796baa9-0420-42cd-86b4-08a72eeb3315

FIXED - Edited class name is not reflecting

---

src/components/SkeltonLoading.tsx

For that Loading Big Chimple Image 
https://github.com/chimple/cuba/issues/2861

Comment chimple_avatar for loading on screen

---

src/pages/Assignment.tsx
src/services/api/ApiHandler.ts
src/services/api/ServiceApi.ts
src/services/api/SqliteApi.ts
src/services/api/SupabaseApi.ts
src/teachers-module/pages/EditClass.tsx
src/teachers-module/pages/HomePage.tsx

- Fix: HomePage now shows updated class data after changing the selected class
- Fix: Removed currentClass prefill logic from "Add New Class" form (only used in "Edit Class")
- Refactor: Optimized updateLessonChapterAndCourseMaps by replacing repeated getChapterById() calls with a single batched API using IN clause

Fix: UI update on class selection & refactor chapter mapping logic

---

src/teachers-module/components/reports/TableRightHeader.tsx
src/teachers-module/components/reports/TableStudentData.tsx

Display Date on Table Header in report page

add previous report pase code

---

src/teachers-module/components/addTeacher/TeacherProfileSection.css

Fix assignment table UI for teacher

---

src/components/IconButton.css
src/components/learningPathway/PathwayModal.css

Popup cross button contains shadow in all the popups which is not necessary and also not mentioned in figma design - Done 
Kannada specials translated text is not displaying properly - Done 
Popup content font weight is still more in kannada - Done

Change some css for UI fix

---

src/teachers-module/pages/LessonDetails.tsx

given onclick support to entire lesson card instead of text

---

src/teachers-module/components/homePage/SideMenu.tsx
src/teachers-module/pages/EditClass.tsx
src/teachers-module/pages/ManageClass.tsx

https://github.com/user-attachments/assets/488e2538-4de8-4696-932b-76f985cdf7c5

Edit Classes Name #2995

---

src/services/api/OneRosterApi.ts

refactored the method :  returning the stored courses for user from local storage.

fix: returning the additional courses  

---

src/components/learningPathway/PathwayModal.css

Add Pathway Modal text font weight 600 in every screen - Done

Add Pathway Modal text font weight

---

src/components/profileDetails/ProfileDetails.tsx
src/pages/Parent.tsx
src/services/api/SupabaseApi.ts

reolving build error

---

src/services/api/SupabaseApi.ts

Updated supabase query in getChapterByLesson()

fix : Unable to assign a recommended assignment for an Ops user

---

src/ops-console/components/Sidebar.css
src/ops-console/components/Sidebar.tsx
src/teachers-module/components/homePage/SideMenu.tsx
src/teachers-module/pages/DisplaySchools.tsx

and switch option to teachers mode in android

Given logout option in ops console 

---

src/components/profileDetails/ProfileDetails.css
src/components/profileDetails/ProfileDetails.tsx
src/pages/DisplayStudents.css

Fixed back button on Edit page

---

src/ops-console/components/Sidebar.css

Navigation bar does not remain fixed and appears in floating state in OPS console issue fix.

CHIM-158 issue fix

---

src/components/ProfileMenu/ProfileMenu.tsx
src/pages/SelectMode.css
src/pages/SelectMode.tsx

feat: At School mode enhancements

---

src/components/learningPathway/ChimpleRiveMascot.tsx

https://github.com/user-attachments/assets/c4649c23-b26a-4406-a773-2442538515e5

chore: set Rive animation to idle state

---

src/services/api/ApiHandler.ts
src/services/api/ServiceApi.ts
src/services/api/SqliteApi.ts
src/services/api/SupabaseApi.ts
src/teachers-module/components/homePage/assignment/CreateSelectedAssignment.tsx
src/teachers-module/components/homePage/assignment/TeacherAssignment.tsx

https://github.com/user-attachments/assets/03c9836c-f18a-4ebe-ae1d-78c394c86bae

Fix: Assign the assignment in background without showing on UI
